# YAML file listing config. parameters
seed: 42
lr: 0.5

# Paths
paths:
  data:
    base_dir: ../data
    data: cfpb.csv
    debug_data: cfpb_debug.csv

# DEBUG [True or False]; if False it will load the debug_data
# Use for pipeline development
debug: False

# DATA
data_info:
  source_fields:
    - Consumer complaint narrative
    - State
    - Company response to consumer
  target: Product

# Stratification Technique
stratify:
  technique: stratified_kfold

# Cross-Validation Folds
cv:
  num_folds: 5
  val_folds: [1, 2, 3, 4, 5] #[list of integers] (start counting at 1)

# Preprocessing
preprocessing:
  apply_techniques:
    - OneHotEncoder
  LabelEncoder:
    fields:
      - Product
  OneHotEncoder:
    fields:
      - Product


# Data
wandb:
  project: nlp-testing
  entity: mdunlap
  log_results: True
  interval_type: steps #[epochs, steps]
  interval_delta: 1 #[int describing numer of intervals]


# Model and Tokenizer
model_tokenizer:
  base_dir: ../hf_download
  name: bert-base-uncased

# Model
model:
  dir: ./utils/models
  module: bert
  func: SillyTest
  freeze:
    apply: True
    num_layers: 10 # Number of layers to freeze starting from layer 1

# Tokenizer
tokenizer:
  abbreviations:
    - Null
  add_special_tokens: True
  max_length: 512
  padding: True
  truncation: True
  return_tensors: pt

# Optimizer
optimizer:
  name: AdamW


# Tuning
batch_size: 4
num_workers: 8
