# YAML file listing config. parameters
seed: 42
lr: 0.5
preprocessing:
  data:
    - clean
    - normalize
    - split
stratify:
  technique: k-fold
  num_folds: 5
  test_folds: all #[all or list of integers]
wandb:
  project: nlp-testing
  entity: mdunlap
  log_results: True
  interval_type: steps #[epochs, steps]
  interval_delta: 1 #[int describing numer of intervals]
data_base_path: './data'

model:
  dir: ./utils/models
  module: bert
  func: SillyTest


