# YAML file listing config. parameters
seed: 42

# Paths
paths:
  data:
    base_dir: ../data
    data: cfpb_partial.csv
    debug_data: cfpb_debug.csv
    partial: cfpb.csv

# DEBUG [True or False]; if False it will load the debug_data
# Use for pipeline development
debug: False

# DATA
data_info:
  source_fields:
    - Consumer complaint narrative
    - Zip code
    - Sub-issue
  target: Product

# Stratification Technique
stratify:
  technique: stratified_kfold

# Cross-Validation Folds
cv:
  num_folds: 5
  val_folds: [1, 2, 3, 4, 5] #[list of integers] (start counting at 1)

# Preprocessing
preprocessing:
  apply_techniques:
    - LabelEncoder
  LabelEncoder:
    fields:
      - Product
  OneHotEncoder:
    fields:
      - Product


# Data
wandb:
  project: nlp-testing
  entity: mdunlap
  log_results: True
  interval_type: steps #[epochs, steps]
  interval_delta: 1 #[int describing numer of intervals]


# Model and Tokenizer
model_tokenizer:
  base_dir: ../hf_download
  name: bert-base-uncased

# Model
model:
  dir: ./utils/models
  module: bert
  func: SillyTest
  freeze:
    apply: False
    # Number of layers to freeze starting from layer 1
    num_layers: 5 
  mean_pooling:
    apply: False
  gradient_checkpointing: False

# Tokenizer
tokenizer:
  abbreviations:
    - Null
  add_special_tokens: True
  max_length: 512
  padding: True
  truncation: True
  return_tensors: pt

# Optimizer
optimizer:
  name: AdamW
  lr:
    min: 1.0E-5
    max: 1.0E-1

# Learning Rate Scheduler
lr_scheduler:
  name: CosineAnnealingLR
  OneCycleLR:
    pct_start: 0.1

# Tuning
epochs: 1
batch_size: 16
num_workers: 8
